services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Inflack@645
      MYSQL_DATABASE: product-manager
      MYSQL_USER: saimon-dev
      MYSQL_PASSWORD: Inflack@645
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: